config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :projects
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 2)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Your article was successfully saved!"
    else
      render 'new', notice: "Unable to save the post."
    end
  end

  def show    
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Your article was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "That project was saved!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "That project was updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kostas Ntallas - Portfolio Page</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="main-navigation" class="clearfix">
      <%= link_to "Kostas Ntallas", root_path, class: "name" %>
        <nav>
          <%= link_to "Articles", posts_path %>
          <%= link_to "Projects", projects_path %>
          <a href="#">Contact</a>
        </nav>
    </header>
    <%= yield %>
    <footer id ="main-footer">
      <p class="copyright">
          &copy; 2019 Kostas Ntallas 
      </p>
      <nav>
          <a href="">
              <i class="fab fa-twitter"></i>
          </a>
          <a href="">
              <i class="fab fa-dribbble"></i>
          </a>
          <a href="">
              <i class="fab fa-github"></i>
          </a>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = '<%= url_for([@post, {only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.shortname = 'blog-portfolio-3';
this.page.title = '<%= @post.title %>';
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://blog-portfolio-3.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :content, "Write your article here" %><br>
  <%= f.text_area :content %>

  <br>
  <br>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page-title">Stuff I've written</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <% @posts.each do |post| %>
    <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
        <h2><a href="#0"><%= link_to post.title, post %></a></h2>
        <hr>
    </div>
  <% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post!</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper-padding">
  <header>
    <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>
  <div id="content">
    <%= markdown @post.content %>
  </div>
  <hr>
  <div id="share-box">
    <p>Share The DO List</p>
    <!-- Twitter -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by Kostas Ntallas-&amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-twitter"></i></a>
    <a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-facebook"></i></a>
    <a onclick="javascript:window.open('http://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-google-plus"></i></a>
  </div>
  <hr>
  <%= render 'disqus' %>
</div>

<br>
<br>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :description %><br>
  <%= f.text_area :description %>

  <br>
  <br>

  <%= f.label :link %><br>
  <%= f.text_field :link %>

  <br>
  <br>

  <%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>Edit Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page-title">Stuff I've written</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <% @projects.each do |project| %>
    <div class="project">
        <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
        <h2><a href="#0"><%= link_to project.title, project %></a></h2>
        <hr>
    </div>
  <% end %>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>New Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper-padding">
  <header>
    <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>
  <div id="content">
    <%= markdown @project.description %>

    <div class="button_wrapper">
      <a href="<%= @project.link %>" class="project_button" target="_blank">
        Visit <%= @project.title %>
      </a>
    </div>
  </div>

  <%= link_to "Edit", edit_project_path(@project) %>
  <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" } %>

  <hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper-padding clearfix">
  <div class="col-1 about homepage-content">
      <h2>About</h2>
      <hr>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          In finibus suscipit molestie. Praesent bibendum purus eget vulputate ultrices. 
          Morbi vestibulum ultrices porta. 
          Duis sed tempus erat. Sed pulvinar gravida lacus ac tincidunt. 
          Morbi porta consectetur mattis. 
          Nulla sit amet lectus convallis, lobortis quam sit amet, pellentesque diam. 
          Integer quis nunc ac nunc pretium laoreet quis in nisi. Mauris molestie ante ante. 
          Nunc ornare diam a lorem porttitor ornare. 
          Nam tristique dictum rhoncus. 
          Nulla fermentum vitae tellus in hendrerit. 
          Praesent nisl erat, facilisis at condimentum vitae, bibendum vel arcu. 
          Quisque sit amet tincidunt <a href="#0">libero</a>.
      </p>
  </div>
  <div class="col-2 homepage-content">
      <h2>Stuff I've written</h2>
      <hr>
      <% @posts.each do |post| %>
        <h3><a href="#"><%= link_to post.title, post %></a></h3>
        <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
      <% end %>
  </div>
  <div class="col-2 homepage-content">
      <h2>Stuff I've build</h2>
      <hr>
        <% @projects.each do |project| %>
        <h3><a href="#"><%= link_to project.title, project %></a></h3>
        <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
      <% end %>
  </div>
</div>